In [47]:
import numpy as np

In [60]:
beta = 1
n_parties = 100

In [ ]:
y_train = []

for i in range(10):
    y_train += [i] * 6000
y_train = np.array(y_train)

In [63]:
import random

random.shuffle(y_train)

In [64]:
min_size = 0
min_require_size = 10
K = 10

N = 60000
np.random.seed(2020)
net_dataidx_map = {}

while min_size < min_require_size:
    print(min_size)
    idx_batch = [[] for _ in range(n_parties)]
    for k in range(K):
        idx_k = np.where(y_train == k)[0]
        
        np.random.shuffle(idx_k)
        proportions = np.random.dirichlet(np.repeat(beta, n_parties))

        proportions = np.array([p * (len(idx_j) < N / n_parties) for p, idx_j in zip(proportions, idx_batch)])

        proportions = proportions / proportions.sum()

        proportions = (np.cumsum(proportions) * len(idx_k)).astype(int)[:-1]

        idx_batch = [idx_j + idx.tolist() for idx_j, idx in zip(idx_batch, np.split(idx_k, proportions))]

        min_size = min([len(idx_j) for idx_j in idx_batch])


for j in range(n_parties):
    np.random.shuffle(idx_batch[j])
    net_dataidx_map[j] = idx_batch[j]

0


In [65]:
total = 0

for i in range(100):
    print(len(net_dataidx_map[i]))
    total += len(net_dataidx_map[i])

print(total)

340
448
526
611
628
969
412
547
698
660
590
664
614
603
633
377
234
619
692
640
488
322
786
619
664
666
621
601
757
766
600
653
649
479
618
485
464
667
687
511
521
606
549
738
617
485
592
548
216
613
519
711
400
617
507
647
594
609
611
617
617
871
674
541
640
693
873
671
861
684
556
579
556
271
671
725
686
865
648
394
645
713
498
611
384
914
406
600
573
471
564
624
705
609
583
642
638
634
527
658
60000


In [1]:
from sklearn.cluster import KMeans
import numpy as np
x = np.random.random(13876)

km = KMeans()
km.fit(x.reshape(-1,1))

KMeans()

In [2]:
km.labels_

array([1, 2, 1, ..., 6, 7, 3], dtype=int32)

In [39]:
i = torch.randn(3, 10, requires_grad=True).detach().numpy()

In [40]:
j = np.mean(i, axis=0)

In [41]:
j

array([ 0.22260378, -0.42252645, -1.8486048 , -0.15425532,  0.47997728,
        0.10177425,  0.01524652, -0.27229467, -1.1926221 ,  0.06527183],
      dtype=float32)

In [45]:
int(np.argmax(j))

4

In [28]:
torch.argmax(torch.mean(i, dim=0, keepdim=False))

tensor(7)

In [21]:
i

tensor([[-0.3351, -0.1475,  0.7482, -1.0834,  1.9886,  0.1873,  0.6571,  0.6890,
         -0.4344, -0.4302],
        [ 1.2028,  0.6174, -0.8184, -1.2145, -0.7562, -1.9102, -1.2260, -0.8585,
         -0.4608,  0.5605],
        [-1.2181,  1.8684,  0.0581, -0.3796,  0.3965,  0.5475,  0.1899,  0.9672,
         -0.7948,  1.2692]], requires_grad=True)

In [48]:

2.0 % 2 == 0

True

In [50]:
int(1.7)

1